### ISSUE TITLE
Initial page visualization issue

### ISSUE THREAD

**Issue by axlt2002** [Varstahl/xbmc#19]
Hi, it is me again. :)

After a while I had the opportunitiy to reinstall all my Kodi stuffs on my media center. I just want to highlight that with the latest Kodi nightly and both 0.5.3 and 0.5.4beta, the initial page of Amazon VOD appears as follow:

https://i.imgur.com/KcJrJzE.jpg

Thanks for the usual great effort you put in this add-on!

**Comment by Varstahl** [comment]
There has been a change in the way PrimeVideo built some of its page, but it's already fixed as per 9a374352cbe166d07d87f8e9303394dbba102bbf. There are another 2 PR with several improvements pending, but Sandmann disappeared so I don't know what to do. You can download the fix from the main repo, it should work fine until we push the update.

**Comment by axlt2002** [comment]
Thanks for the answer Varstahl, but I have still one doubt. I have downloaded the latest test version from your github (0.5.4 beta) but the problem is still there...what Am I missing? Should I have to reinstall it from the scratch instead of updating the 0.5.3?

**Comment by Varstahl** [comment]
I don't really bump the version number so that is no indicator, but you should be able to pick the [default.py](https://github.com/Varstahl/xbmc/blob/master/plugin.video.amazon-test/default.py) from the main branch and it "should" fix it. If it doesn't work for you either something went wrong or there's still a bug. Can you re-test it with the provided link version?

**Comment by axlt2002** [comment]
Removing the cache made the trick! Thanks a lot! ;)
